from fastapi import FastAPI # Import FastAPI class from fastapi module
from app.database import engine
from backend.app.models import Task # Import the database engine

app = FastAPI() # Create an instance of FastAPI

@app.get("/health") # Define a GET endpoint at /health
def health(): # Define the health function
    return {"status": "OK"} # Return a JSON response indicating the service is healthy

@app.get("/tasks") # Registers a GET endpoint at /tasks
def get_tasks(db: Session = Depends(get_db)): # FastAPI calls get_db(), injects a DB session and cleans it up after the request
    tasks = db.query(Task).all() # Query all tasks from the database, translates to SQL: SELECT * FROM tasks; "ORM -> SQL -> DB -> SQL Result -> ORM Objects"
    return tasks # Return the list of tasks as JSON

@app.post("/tasks") # Registers a POST endpoint at /tasks
def create_task(task_data: dict, db: Session=Depends(get_data)): # FastAPI calls get_db(), injects a DB session and cleans it up after the request
    task=Task(**task_data) # Create a new Task instance from the provided data
    db.add(task) # Stage the new task for insertion into the db, does not hit the DB yet
    db.commit() # Executes SQL INSERT, permanently stores data
    db.refresh(task) # Reloads data from db to get any autogenerated db fields (like ID,timestamps),REFRESH: To sync ORM object with DB-generated values.
    return task # Return the newly created task as JSON